///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelSmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Connect recording.
    /// </summary>
    [TestModule("bf8d7e59-9b86-4743-a541-1b855808c10c", ModuleType.Recording, 1)]
    public partial class Connect : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelSmokeTestRepository repository.
        /// </summary>
        public static ExcelSmokeTestRepository repo = ExcelSmokeTestRepository.Instance;

        static Connect instance = new Connect();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Connect()
        {
            C5 = "586";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Connect Instance
        {
            get { return instance; }
        }

#region Variables

        string _C5;

        /// <summary>
        /// Gets or sets the value of variable C5.
        /// </summary>
        [TestVariable("debb450a-c69c-44af-bcac-2a640994423a")]
        public string C5
        {
            get { return _C5; }
            set { _C5 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Connect' at 20;24.", repo.Excel.ConnectInfo, new RecordItemIndex(0));
            repo.Excel.Connect.Click("20;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.ToggleButton' at 331;12.", repo.Excel.ToggleButtonInfo, new RecordItemIndex(1));
            repo.Excel.ToggleButton.Click("331;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EXCEL1.SomeListItem' at 157;15.", repo.EXCEL1.SomeListItemInfo, new RecordItemIndex(2));
            repo.EXCEL1.SomeListItem.Click("157;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.CompteDeResultat' at 121;11.", repo.Excel.CompteDeResultatInfo, new RecordItemIndex(3));
            repo.Excel.CompteDeResultat.Click("121;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.CompteDeResultat1' at 107;9.", repo.Excel.CompteDeResultat1Info, new RecordItemIndex(4));
            repo.Excel.CompteDeResultat1.Click("107;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Next' at 54;5.", repo.Excel.NextInfo, new RecordItemIndex(5));
            repo.Excel.Next.Click("54;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Excel.Frame1.SomeListItem' at 130;19.", repo.Excel.Frame1.SomeListItemInfo, new RecordItemIndex(6));
            repo.Excel.Frame1.SomeListItem.MoveTo("130;19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Excel.Frame1.SomeListItem' at 138;11.", repo.Excel.Frame1.SomeListItemInfo, new RecordItemIndex(7));
            repo.Excel.Frame1.SomeListItem.MoveTo("138;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Excel.Frame1.RowsList' at 97;117.", repo.Excel.Frame1.RowsListInfo, new RecordItemIndex(8));
            repo.Excel.Frame1.RowsList.MoveTo("97;117");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Excel.Frame1.DimTextBlock' at 33;3.", repo.Excel.Frame1.DimTextBlockInfo, new RecordItemIndex(9));
            repo.Excel.Frame1.DimTextBlock.MoveTo("33;3");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Excel.Frame1.DimTextBlock' at 41;-5.", repo.Excel.Frame1.DimTextBlockInfo, new RecordItemIndex(10));
            repo.Excel.Frame1.DimTextBlock.MoveTo("41;-5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Excel.Frame1.ColumnsList' at 85;112.", repo.Excel.Frame1.ColumnsListInfo, new RecordItemIndex(11));
            repo.Excel.Frame1.ColumnsList.MoveTo("85;112");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Finish' at 46;22.", repo.Excel.FinishInfo, new RecordItemIndex(12));
            repo.Excel.Finish.Click("46;22");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
