///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExcelSmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ExcelSmokeTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("3913e735-eb9a-4991-8cae-af070800596a")]
    public partial class ExcelSmokeTestRepository : RepoGenBaseFolder
    {
        static ExcelSmokeTestRepository instance = new ExcelSmokeTestRepository();
        ExcelSmokeTestRepositoryFolders.ExcelAppFolder _excel;
        ExcelSmokeTestRepositoryFolders.GettingStartedServingWebContentAppFolder _gettingstartedservingwebcontent;
        ExcelSmokeTestRepositoryFolders.EXCEL1AppFolder _excel1;

        /// <summary>
        /// Gets the singleton class instance representing the ExcelSmokeTestRepository element repository.
        /// </summary>
        [RepositoryFolder("3913e735-eb9a-4991-8cae-af070800596a")]
        public static ExcelSmokeTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ExcelSmokeTestRepository() 
            : base("ExcelSmokeTestRepository", "/", null, 0, false, "3913e735-eb9a-4991-8cae-af070800596a", ".\\RepositoryImages\\ExcelSmokeTestRepository3913e735.rximgres")
        {
            _excel = new ExcelSmokeTestRepositoryFolders.ExcelAppFolder(this);
            _gettingstartedservingwebcontent = new ExcelSmokeTestRepositoryFolders.GettingStartedServingWebContentAppFolder(this);
            _excel1 = new ExcelSmokeTestRepositoryFolders.EXCEL1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3913e735-eb9a-4991-8cae-af070800596a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Excel folder.
        /// </summary>
        [RepositoryFolder("91c6168c-60b7-4cdf-b66e-b91fcce2656e")]
        public virtual ExcelSmokeTestRepositoryFolders.ExcelAppFolder Excel
        {
            get { return _excel; }
        }

        /// <summary>
        /// The GettingStartedServingWebContent folder.
        /// </summary>
        [RepositoryFolder("3b077bf6-c6fd-44f2-8cdc-7d6c5676c0ac")]
        public virtual ExcelSmokeTestRepositoryFolders.GettingStartedServingWebContentAppFolder GettingStartedServingWebContent
        {
            get { return _gettingstartedservingwebcontent; }
        }

        /// <summary>
        /// The EXCEL1 folder.
        /// </summary>
        [RepositoryFolder("c1772ee2-c41d-45ec-8690-d1690e6fffb5")]
        public virtual ExcelSmokeTestRepositoryFolders.EXCEL1AppFolder EXCEL1
        {
            get { return _excel1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class ExcelSmokeTestRepositoryFolders
    {
        /// <summary>
        /// The ExcelAppFolder folder.
        /// </summary>
        [RepositoryFolder("91c6168c-60b7-4cdf-b66e-b91fcce2656e")]
        public partial class ExcelAppFolder : RepoGenBaseFolder
        {
            ExcelSmokeTestRepositoryFolders.FrameFolder _frame;
            ExcelSmokeTestRepositoryFolders.Frame1Folder _frame1;
            RepoItemInfo _aiostartdocumentInfo;
            RepoItemInfo _anaplanInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _togglebuttonInfo;
            RepoItemInfo _connectInfo;
            RepoItemInfo _comptederesultatInfo;
            RepoItemInfo _comptederesultat1Info;
            RepoItemInfo _nextInfo;
            RepoItemInfo _finishInfo;
            RepoItemInfo _netuihwndInfo;
            RepoItemInfo _paneInfo;
            RepoItemInfo _containernewInfo;

            /// <summary>
            /// Creates a new Excel  folder.
            /// </summary>
            public ExcelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Excel", "/form[@processname='EXCEL']", parentFolder, 30000, null, false, "91c6168c-60b7-4cdf-b66e-b91fcce2656e", "")
            {
                _frame = new ExcelSmokeTestRepositoryFolders.FrameFolder(this);
                _frame1 = new ExcelSmokeTestRepositoryFolders.Frame1Folder(this);
                _aiostartdocumentInfo = new RepoItemInfo(this, "AIOStartDocument", ".//container[@automationid='BackstageView']/?/?/container[@name='New']/container[@name='Featured']/button[@name='Blank workbook']", 30000, null, "f0b6946f-97f5-4bf4-8ee9-8c3a8196e9e8");
                _anaplanInfo = new RepoItemInfo(this, "Anaplan", "element[2]//container[@name='Ribbon']/tabpagelist[@name='Ribbon Tabs']/tabpage[@name='Anaplan']", 30000, null, "b5a40bf3-e4a2-4f48-9aee-323db38607e1");
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/element[@name='Anaplan']/container[@name='Access']/button[@name='Log In']", 30000, null, "db72e645-c4f0-4802-8cb0-48851acb6e36");
                _usernameInfo = new RepoItemInfo(this, "Username", "container[@automationid='Frame']/?/?/text[@automationid='Username']", 30000, null, "3b9d9ea3-ce23-4a45-a940-760f7e2e8a50");
                _passwordInfo = new RepoItemInfo(this, "Password", "container[@automationid='Frame']/?/?/text[@automationid='Password']", 30000, null, "486fad76-f960-482f-9a35-cd41e164d634");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "container[@automationid='Frame']//button[@automationid='Ok']", 10000, null, "f7f14d72-f360-4883-b160-ae9cf4e16652");
                _togglebuttonInfo = new RepoItemInfo(this, "ToggleButton", "?/?/container[@automationid='Frame']/?/?/combobox[@automationid='workspaces']/button[@automationid='ToggleButton']", 30000, null, "fb9585f8-75d6-44ed-8365-a9891f1a99b3");
                _connectInfo = new RepoItemInfo(this, "Connect", ".//container[@name='Ribbon']/container[@name='Lower Ribbon']/element[@name='Anaplan']/container[@name='Data']/button[@name='Connect']/button[@name='Connect']", 10000, null, "912a6ead-e5c0-45fa-a6a5-77ef71dead87");
                _comptederesultatInfo = new RepoItemInfo(this, "CompteDeResultat", "?/?/container[@automationid='Frame']/?/?/container[@automationid='ModelsTable']/list[@automationid='FilterableTable']/?/?/text[@caption='Compte_de_resultat']", 30000, null, "70c73862-8794-4811-9794-619264281c9e");
                _comptederesultat1Info = new RepoItemInfo(this, "CompteDeResultat1", "?/?/container[@automationid='Frame']/?/?/container[@automationid='ModulesTable']/list[@automationid='FilterableTable']//text[@caption='Compte_de_resultat']", 30000, null, "b2eb0f5f-0ec4-4d5d-92e7-051f039465bd");
                _nextInfo = new RepoItemInfo(this, "Next", "container[1]/?/?/button[@automationid='Next']", 30000, null, "7110212f-5341-46d9-9ebd-a14471963cf1");
                _finishInfo = new RepoItemInfo(this, "Finish", "container[1]/?/?/button[@automationid='Finish']", 30000, null, "c94dc0a7-77f2-496f-a928-d47519c82b7f");
                _netuihwndInfo = new RepoItemInfo(this, "NetUIHWND", "element[@class='FullpageUIHost']/container[@class='NetUIHWND']", 30000, null, "e9aa8f0e-d6e0-42ee-a6d3-e5dbdc394b55");
                _paneInfo = new RepoItemInfo(this, "Pane", "element[@class='FullpageUIHost']/?/?/container[@accessiblename='']", 30000, null, "0afc0386-a0fe-46ce-ac98-5f489b8a2e02");
                _containernewInfo = new RepoItemInfo(this, "ContainerNew", ".//container[@automationid='BackstageView']/container[@name='New']/container[@name='New']", 30000, null, "58633bcc-a729-4228-bc43-7a4ddbc3ec2e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91c6168c-60b7-4cdf-b66e-b91fcce2656e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91c6168c-60b7-4cdf-b66e-b91fcce2656e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AIOStartDocument item.
            /// </summary>
            [RepositoryItem("f0b6946f-97f5-4bf4-8ee9-8c3a8196e9e8")]
            public virtual Ranorex.Button AIOStartDocument
            {
                get
                {
                    return _aiostartdocumentInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AIOStartDocument item info.
            /// </summary>
            [RepositoryItemInfo("f0b6946f-97f5-4bf4-8ee9-8c3a8196e9e8")]
            public virtual RepoItemInfo AIOStartDocumentInfo
            {
                get
                {
                    return _aiostartdocumentInfo;
                }
            }

            /// <summary>
            /// The Anaplan item.
            /// </summary>
            [RepositoryItem("b5a40bf3-e4a2-4f48-9aee-323db38607e1")]
            public virtual Ranorex.TabPage Anaplan
            {
                get
                {
                    return _anaplanInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Anaplan item info.
            /// </summary>
            [RepositoryItemInfo("b5a40bf3-e4a2-4f48-9aee-323db38607e1")]
            public virtual RepoItemInfo AnaplanInfo
            {
                get
                {
                    return _anaplanInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("db72e645-c4f0-4802-8cb0-48851acb6e36")]
            public virtual Ranorex.Button LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("db72e645-c4f0-4802-8cb0-48851acb6e36")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("3b9d9ea3-ce23-4a45-a940-760f7e2e8a50")]
            public virtual Ranorex.Text Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("3b9d9ea3-ce23-4a45-a940-760f7e2e8a50")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("486fad76-f960-482f-9a35-cd41e164d634")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("486fad76-f960-482f-9a35-cd41e164d634")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("f7f14d72-f360-4883-b160-ae9cf4e16652")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("f7f14d72-f360-4883-b160-ae9cf4e16652")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ToggleButton item.
            /// </summary>
            [RepositoryItem("fb9585f8-75d6-44ed-8365-a9891f1a99b3")]
            public virtual Ranorex.Button ToggleButton
            {
                get
                {
                    return _togglebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ToggleButton item info.
            /// </summary>
            [RepositoryItemInfo("fb9585f8-75d6-44ed-8365-a9891f1a99b3")]
            public virtual RepoItemInfo ToggleButtonInfo
            {
                get
                {
                    return _togglebuttonInfo;
                }
            }

            /// <summary>
            /// The Connect item.
            /// </summary>
            [RepositoryItem("912a6ead-e5c0-45fa-a6a5-77ef71dead87")]
            public virtual Ranorex.Button Connect
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Connect item info.
            /// </summary>
            [RepositoryItemInfo("912a6ead-e5c0-45fa-a6a5-77ef71dead87")]
            public virtual RepoItemInfo ConnectInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The CompteDeResultat item.
            /// </summary>
            [RepositoryItem("70c73862-8794-4811-9794-619264281c9e")]
            public virtual Ranorex.Text CompteDeResultat
            {
                get
                {
                    return _comptederesultatInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CompteDeResultat item info.
            /// </summary>
            [RepositoryItemInfo("70c73862-8794-4811-9794-619264281c9e")]
            public virtual RepoItemInfo CompteDeResultatInfo
            {
                get
                {
                    return _comptederesultatInfo;
                }
            }

            /// <summary>
            /// The CompteDeResultat1 item.
            /// </summary>
            [RepositoryItem("b2eb0f5f-0ec4-4d5d-92e7-051f039465bd")]
            public virtual Ranorex.Text CompteDeResultat1
            {
                get
                {
                    return _comptederesultat1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CompteDeResultat1 item info.
            /// </summary>
            [RepositoryItemInfo("b2eb0f5f-0ec4-4d5d-92e7-051f039465bd")]
            public virtual RepoItemInfo CompteDeResultat1Info
            {
                get
                {
                    return _comptederesultat1Info;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("7110212f-5341-46d9-9ebd-a14471963cf1")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("7110212f-5341-46d9-9ebd-a14471963cf1")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("c94dc0a7-77f2-496f-a928-d47519c82b7f")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("c94dc0a7-77f2-496f-a928-d47519c82b7f")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The NetUIHWND item.
            /// </summary>
            [RepositoryItem("e9aa8f0e-d6e0-42ee-a6d3-e5dbdc394b55")]
            public virtual Ranorex.Container NetUIHWND
            {
                get
                {
                    return _netuihwndInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NetUIHWND item info.
            /// </summary>
            [RepositoryItemInfo("e9aa8f0e-d6e0-42ee-a6d3-e5dbdc394b55")]
            public virtual RepoItemInfo NetUIHWNDInfo
            {
                get
                {
                    return _netuihwndInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("0afc0386-a0fe-46ce-ac98-5f489b8a2e02")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("0afc0386-a0fe-46ce-ac98-5f489b8a2e02")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The ContainerNew item.
            /// </summary>
            [RepositoryItem("58633bcc-a729-4228-bc43-7a4ddbc3ec2e")]
            public virtual Ranorex.Container ContainerNew
            {
                get
                {
                    return _containernewInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerNew item info.
            /// </summary>
            [RepositoryItemInfo("58633bcc-a729-4228-bc43-7a4ddbc3ec2e")]
            public virtual RepoItemInfo ContainerNewInfo
            {
                get
                {
                    return _containernewInfo;
                }
            }

            /// <summary>
            /// The Frame folder.
            /// </summary>
            [RepositoryFolder("26013715-4b48-48e6-b28b-fd39a7eaab08")]
            public virtual ExcelSmokeTestRepositoryFolders.FrameFolder Frame
            {
                get { return _frame; }
            }

            /// <summary>
            /// The Frame1 folder.
            /// </summary>
            [RepositoryFolder("00255fbc-afa4-4438-8741-aff4f31826c6")]
            public virtual ExcelSmokeTestRepositoryFolders.Frame1Folder Frame1
            {
                get { return _frame1; }
            }
        }

        /// <summary>
        /// The FrameFolder folder.
        /// </summary>
        [RepositoryFolder("26013715-4b48-48e6-b28b-fd39a7eaab08")]
        public partial class FrameFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Frame  folder.
            /// </summary>
            public FrameFolder(RepoGenBaseFolder parentFolder) :
                    base("Frame", "container[@automationid='Frame']", parentFolder, 30000, null, false, "26013715-4b48-48e6-b28b-fd39a7eaab08", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("26013715-4b48-48e6-b28b-fd39a7eaab08")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("26013715-4b48-48e6-b28b-fd39a7eaab08")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The Frame1Folder folder.
        /// </summary>
        [RepositoryFolder("00255fbc-afa4-4438-8741-aff4f31826c6")]
        public partial class Frame1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _somelistitemInfo;
            RepoItemInfo _columnslistInfo;
            RepoItemInfo _rowslistInfo;
            RepoItemInfo _dimtextblockInfo;

            /// <summary>
            /// Creates a new Frame1  folder.
            /// </summary>
            public Frame1Folder(RepoGenBaseFolder parentFolder) :
                    base("Frame1", "?/?/container[@automationid='Frame']", parentFolder, 30000, null, false, "00255fbc-afa4-4438-8741-aff4f31826c6", "")
            {
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", "?/?/list[@automationid='AvailablesList']/?/?/listitem[@index='0']", 30000, null, "838a9563-5d93-4928-9820-479a5202f478");
                _columnslistInfo = new RepoItemInfo(this, "ColumnsList", "text[@automationid='AvailablesLabel']/?/?/list[@automationid='ColumnsList']", 30000, null, "6144bf31-10ff-43a4-b492-8e6eff763d16");
                _rowslistInfo = new RepoItemInfo(this, "RowsList", "text[@automationid='AvailablesLabel']/?/?/list[@automationid='RowsList']", 30000, null, "08b28292-a722-4f80-bc77-41e2a5a75ed9");
                _dimtextblockInfo = new RepoItemInfo(this, "DimTextBlock", "text[@automationid='AvailablesLabel']/list[@automationid='AvailablesList']//text[@automationid='DimTextBlock']", 30000, null, "9752fd12-8352-42e2-b280-0fdf9cce1b48");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00255fbc-afa4-4438-8741-aff4f31826c6")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00255fbc-afa4-4438-8741-aff4f31826c6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("838a9563-5d93-4928-9820-479a5202f478")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("838a9563-5d93-4928-9820-479a5202f478")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }

            /// <summary>
            /// The ColumnsList item.
            /// </summary>
            [RepositoryItem("6144bf31-10ff-43a4-b492-8e6eff763d16")]
            public virtual Ranorex.List ColumnsList
            {
                get
                {
                    return _columnslistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The ColumnsList item info.
            /// </summary>
            [RepositoryItemInfo("6144bf31-10ff-43a4-b492-8e6eff763d16")]
            public virtual RepoItemInfo ColumnsListInfo
            {
                get
                {
                    return _columnslistInfo;
                }
            }

            /// <summary>
            /// The RowsList item.
            /// </summary>
            [RepositoryItem("08b28292-a722-4f80-bc77-41e2a5a75ed9")]
            public virtual Ranorex.List RowsList
            {
                get
                {
                    return _rowslistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The RowsList item info.
            /// </summary>
            [RepositoryItemInfo("08b28292-a722-4f80-bc77-41e2a5a75ed9")]
            public virtual RepoItemInfo RowsListInfo
            {
                get
                {
                    return _rowslistInfo;
                }
            }

            /// <summary>
            /// The DimTextBlock item.
            /// </summary>
            [RepositoryItem("9752fd12-8352-42e2-b280-0fdf9cce1b48")]
            public virtual Ranorex.Text DimTextBlock
            {
                get
                {
                    return _dimtextblockInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DimTextBlock item info.
            /// </summary>
            [RepositoryItemInfo("9752fd12-8352-42e2-b280-0fdf9cce1b48")]
            public virtual RepoItemInfo DimTextBlockInfo
            {
                get
                {
                    return _dimtextblockInfo;
                }
            }
        }

        /// <summary>
        /// The GettingStartedServingWebContentAppFolder folder.
        /// </summary>
        [RepositoryFolder("3b077bf6-c6fd-44f2-8cdc-7d6c5676c0ac")]
        public partial class GettingStartedServingWebContentAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _authorizeInfo;

            /// <summary>
            /// Creates a new GettingStartedServingWebContent  folder.
            /// </summary>
            public GettingStartedServingWebContentAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GettingStartedServingWebContent", "/dom[@domain='ec2-extensionsapitest1-1-paris5.anaplan.com']", parentFolder, 30000, null, false, "3b077bf6-c6fd-44f2-8cdc-7d6c5676c0ac", "")
            {
                _authorizeInfo = new RepoItemInfo(this, "Authorize", ".//form[#'confirmationForm']/?/?/input[@name='authorize']", 30000, null, "9fd27ded-a88e-4293-8969-788623a78630");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3b077bf6-c6fd-44f2-8cdc-7d6c5676c0ac")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3b077bf6-c6fd-44f2-8cdc-7d6c5676c0ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Authorize item.
            /// </summary>
            [RepositoryItem("9fd27ded-a88e-4293-8969-788623a78630")]
            public virtual Ranorex.InputTag Authorize
            {
                get
                {
                    return _authorizeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Authorize item info.
            /// </summary>
            [RepositoryItemInfo("9fd27ded-a88e-4293-8969-788623a78630")]
            public virtual RepoItemInfo AuthorizeInfo
            {
                get
                {
                    return _authorizeInfo;
                }
            }
        }

        /// <summary>
        /// The EXCEL1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c1772ee2-c41d-45ec-8690-d1690e6fffb5")]
        public partial class EXCEL1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somelistitemInfo;

            /// <summary>
            /// Creates a new EXCEL1  folder.
            /// </summary>
            public EXCEL1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("EXCEL1", "/contextmenu[@processname='EXCEL']", parentFolder, 30000, null, false, "c1772ee2-c41d-45ec-8690-d1690e6fffb5", "")
            {
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", "listitem[@index='0']", 30000, null, "3b8763bb-ddcb-490e-bf71-8e810e91d051");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c1772ee2-c41d-45ec-8690-d1690e6fffb5")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c1772ee2-c41d-45ec-8690-d1690e6fffb5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("3b8763bb-ddcb-490e-bf71-8e810e91d051")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("3b8763bb-ddcb-490e-bf71-8e810e91d051")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}