///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelSmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("f6000ca7-5d9d-4937-acd5-07679e885220", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelSmokeTestRepository repository.
        /// </summary>
        public static ExcelSmokeTestRepository repo = ExcelSmokeTestRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.LogIn' at 19;29.", repo.Excel.LogInInfo, new RecordItemIndex(0));
            repo.Excel.LogIn.Click("19;29");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Username' at 133;27.", repo.Excel.UsernameInfo, new RecordItemIndex(1));
            repo.Excel.Username.Click("133;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'michael.atkins{RShiftKey down}@{RShiftKey up}anaplan.com'.", new RecordItemIndex(2));
            Keyboard.Press("michael.atkins{RShiftKey down}@{RShiftKey up}anaplan.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.Password' at 115;24.", repo.Excel.PasswordInfo, new RecordItemIndex(3));
            repo.Excel.Password.Click("115;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}!Y{LShiftKey up}erdan42876666{RShiftKey down}!{RShiftKey up}'.", new RecordItemIndex(4));
            Keyboard.Press("{LShiftKey down}!Y{LShiftKey up}erdan42876666{RShiftKey down}!{RShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Excel.ButtonOk' at 51;18.", repo.Excel.ButtonOkInfo, new RecordItemIndex(5));
            repo.Excel.ButtonOk.Click("51;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GettingStartedServingWebContent.Authorize' at 45;15.", repo.GettingStartedServingWebContent.AuthorizeInfo, new RecordItemIndex(6));
            repo.GettingStartedServingWebContent.Authorize.Click("45;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
